name = input("Enter your name:")
age = int(input("Enter your age:"))
course = input("Enter your course:")
college = input("Enter your college name:")
email = input("Enter your Email ID:")

print("╔════════════════════╗")
print("║  STUDENT BIO CARD  ║")
print("╠════════════════════╣")
print("Name   :", name)
print("Age    :", age)
print("Course :", course)
print("College:", college)
print("Email  :", email)
print("╚════════════════════╝")